api_version = "2024-10"  # ✅ Fixed: Changed from "2025-04" to "2024-10"

[[extensions]]
name = "Book at Rushrr"
handle = "admin-action-123"
type = "ui_extension"

[[extensions.targeting]]
target = "admin.order-index.selection-action.render"
module = "./src/ActionExtension.jsx"