# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d948c39ace52ca077a83e797dd44713a"
name = "rushrr-new-app"
handle = "rushrr-new-app"
application_url = "https://enquiries-agricultural-switched-answering.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_products"

[auth]
redirect_urls = ["https://enquiries-agricultural-switched-answering.trycloudflare.com/auth/callback", "https://enquiries-agricultural-switched-answering.trycloudflare.com/auth/shopify/callback", "https://enquiries-agricultural-switched-answering.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
